import type { SourceRegistryInput } from "@/src/product/sourceRegistry";

export const turkeyCuratedSources: SourceRegistryInput[] = [
  {
    id: "tr-source-bbc-turkce",
    name: "BBC Türkçe",
    type: "Newswire",
    coverage: "Turkey politics / economy / society - international standards",
    credibility: "High",
    role: "Validation source - cross-check",
    domains: ["bbc.com/turkce", "x-account:bbcturkce"],
    status: "Active",
    notes:
      "Use as credibility anchor. Compare with local sources when stories conflict. Handle: @bbcturkce.",
  },
  {
    id: "tr-source-deutsche-welle-turkce",
    name: "Deutsche Welle Türkçe",
    type: "Newswire",
    coverage: "Turkey politics / EU relations / human rights",
    credibility: "High",
    role: "Validation source - cross-check",
    domains: ["dw.com/tr", "x-account:dw_turkce"],
    status: "Active",
    notes:
      "Strong editorial independence. Good for sensitive political stories. Handle: @dw_turkce.",
  },
  {
    id: "tr-source-voa-turkce",
    name: "VOA Türkçe",
    type: "Newswire",
    coverage: "Turkey politics / US-Turkey relations / democracy",
    credibility: "High",
    role: "Validation source",
    domains: ["voaturkish.com", "x-account:VOATurkce"],
    status: "Active",
    notes:
      "US state-funded but editorially independent. Good for diplomatic stories. Handle: @VOATurkce.",
  },
  {
    id: "tr-source-independent-turkce",
    name: "Independent Türkçe",
    type: "Newswire",
    coverage: "Turkey politics / economy / international",
    credibility: "High",
    role: "Validation source",
    domains: ["indyturk.com", "x-account:indyturkiye"],
    status: "Active",
    notes: "UK Independent affiliate. Good international framing. Handle: @indyturkiye.",
  },
  {
    id: "tr-source-medyascope",
    name: "Medyascope",
    type: "Local press",
    coverage: "Turkey politics / media freedom / investigative",
    credibility: "High",
    role: "Early signal - deep background",
    domains: ["medyascope.tv", "x-account:medyascope"],
    status: "Active",
    notes:
      "Investigative. Slower but reliable. Good for context on breaking news. Handle: @medyascope.",
  },
  {
    id: "tr-source-bianet",
    name: "Bianet",
    type: "Local press",
    coverage: "Human rights / press freedom / minority issues",
    credibility: "High",
    role: "Specialized signal",
    domains: ["bianet.org", "x-account:bianet_org"],
    status: "Active",
    notes: "Use for human rights angle. Not general news - niche coverage. Handle: @bianet_org.",
  },
  {
    id: "tr-source-t24",
    name: "T24",
    type: "Local press",
    coverage: "Turkey politics / economy / general news",
    credibility: "Medium",
    role: "Early signal",
    domains: ["t24.com.tr", "x-account:t24com"],
    status: "Active",
    notes:
      "Generally reliable. Occasional editorial slant. Cross-check political stories. Handle: @t24com.",
  },
  {
    id: "tr-source-bloomberg-ht",
    name: "Bloomberg HT",
    type: "Local press",
    coverage: "Turkey macro / FX / markets / inflation",
    credibility: "High",
    role: "Resolution source - market data",
    domains: ["bloomberght.com", "x-account:bloomberght"],
    status: "Active",
    notes:
      "Primary source for economic and financial market stories. Handle: @bloomberght.",
  },
  {
    id: "tr-source-dunya-gazetesi",
    name: "Dünya Gazetesi",
    type: "Local press",
    coverage: "Turkey business / trade / economy",
    credibility: "High",
    role: "Resolution source",
    domains: ["dunya.com", "x-account:dunyacom"],
    status: "Active",
    notes: "Business-focused. Reliable for trade and corporate news. Handle: @dunyacom.",
  },
  {
    id: "tr-source-ekonomist",
    name: "Ekonomist",
    type: "Local press",
    coverage: "Turkey economy / analysis",
    credibility: "High",
    role: "Deep background",
    domains: ["ekonomist.com.tr", "x-account:ekonomistcom"],
    status: "Active",
    notes: "Analysis-heavy. Slower cycle. Use for context not breaking. Handle: @ekonomistcom.",
  },
  {
    id: "tr-source-ahval-news",
    name: "Ahval News",
    type: "Local press",
    coverage: "Turkey politics / economy - English/Arabic",
    credibility: "Medium",
    role: "Validation source",
    domains: ["ahvalnews.com", "x-account:ahvalnews"],
    status: "Active",
    notes:
      "English language. Useful for international audience monitoring. Handle: @ahvalnews.",
  },
  {
    id: "tr-source-gazete-duvar",
    name: "Gazete Duvar",
    type: "Local press",
    coverage: "Turkey politics / social issues",
    credibility: "Medium",
    role: "Early signal",
    domains: ["gazeteduvar.com.tr", "x-account:gazeteduvar"],
    status: "Needs curation",
    notes:
      "Opposition-leaning. Useful for political opposition angle. Verify before use. Handle: @gazeteduvar.",
  },
  {
    id: "tr-source-cumhuriyet",
    name: "Cumhuriyet",
    type: "Local press",
    coverage: "Turkey politics / economy / general",
    credibility: "Medium",
    role: "Early signal",
    domains: ["cumhuriyet.com.tr", "x-account:cumhuriyetgzt"],
    status: "Needs curation",
    notes:
      "Opposition/secular. Useful for anti-government angle. Verify political claims. Handle: @cumhuriyetgzt.",
  },
  {
    id: "tr-source-sozcu",
    name: "Sözcü",
    type: "Local press",
    coverage: "Turkey politics / general news",
    credibility: "Medium",
    role: "Sentiment signal",
    domains: ["sozcu.com.tr", "x-account:sozcu_gazetesi"],
    status: "Needs curation",
    notes:
      "Large readership. Opposition. Good for public sentiment gauge. Handle: @sozcu_gazetesi.",
  },
  {
    id: "tr-source-hurriyet",
    name: "Hürriyet",
    type: "Local press",
    coverage: "Turkey general news / politics / economy",
    credibility: "Medium",
    role: "Mainstream signal",
    domains: ["hurriyet.com.tr", "x-account:hurriyet"],
    status: "Watch",
    notes: "Major mainstream outlet. Pro-government lean. Use for official narrative only. Handle: @hurriyet.",
  },
  {
    id: "tr-source-ntv",
    name: "NTV",
    type: "Local press",
    coverage: "Turkey breaking news / economy / politics",
    credibility: "Medium",
    role: "Mainstream signal - early breaking",
    domains: ["ntv.com.tr", "x-account:ntvturkiye"],
    status: "Watch",
    notes:
      "Broad coverage. Good for breaking news speed. Verify political framing. Handle: @ntvturkiye.",
  },
  {
    id: "tr-source-cnn-turk",
    name: "CNN Türk",
    type: "Local press",
    coverage: "Turkey breaking news / general",
    credibility: "Medium",
    role: "Mainstream signal",
    domains: ["cnnturk.com", "x-account:cnnturk"],
    status: "Watch",
    notes: "High traffic. Pro-government lean. Use as mainstream pulse only. Handle: @cnnturk.",
  },
  {
    id: "tr-source-rusen-cakir",
    name: "Ruşen Çakır",
    type: "X account",
    coverage: "Turkey politics / analysis",
    credibility: "High",
    role: "Deep background - validation",
    domains: ["x-account:rusencakir", "rusencakir.com"],
    status: "Active",
    notes:
      "One of the more balanced voices. Good for context on complex political stories. Handle: @rusencakir.",
  },
  {
    id: "tr-source-kadri-gursel",
    name: "Kadri Gürsel",
    type: "X account",
    coverage: "Turkey politics / media freedom",
    credibility: "High",
    role: "Validation source",
    domains: ["x-account:kadrigursel"],
    status: "Active",
    notes:
      "Independent and credible. Flags media freedom issues early. Handle: @kadrigursel.",
  },
  {
    id: "tr-source-bulent-mumay",
    name: "Bülent Mumay",
    type: "X account",
    coverage: "Press freedom / journalism",
    credibility: "High",
    role: "Specialized signal",
    domains: ["x-account:bulent_mumay"],
    status: "Active",
    notes:
      "Tracks journalist arrests and censorship in real time. Niche but reliable. Handle: @bulent_mumay.",
  },
  {
    id: "tr-source-ugur-gurses",
    name: "Uğur Gürses",
    type: "X account",
    coverage: "Turkey FX / monetary policy / TCMB",
    credibility: "High",
    role: "Resolution source - early signal",
    domains: ["x-account:ugurses"],
    status: "Active",
    notes: "Former central banker. Primary signal for TCMB and FX policy moves. Handle: @ugurses.",
  },
  {
    id: "tr-source-mahfi-egilmez",
    name: "Mahfi Eğilmez",
    type: "X account",
    coverage: "Turkey macro / fiscal policy / inflation",
    credibility: "High",
    role: "Deep background",
    domains: ["x-account:mahfiegilmez", "mahfiegilmez.com"],
    status: "Active",
    notes:
      "Retired bureaucrat. Authoritative on budget and macro policy. Handle: @mahfiegilmez.",
  },
  {
    id: "tr-source-fehim-tastekin",
    name: "Fehim Taştekin",
    type: "X account",
    coverage: "Turkey foreign policy / Syria / Middle East",
    credibility: "High",
    role: "Specialized signal",
    domains: ["x-account:fehimtastekin"],
    status: "Active",
    notes:
      "Best single source for Turkey-Syria and regional foreign policy. Handle: @fehimtastekin.",
  },
  {
    id: "tr-source-amberin-zaman",
    name: "Amberin Zaman",
    type: "X account",
    coverage: "Turkey politics / Kurds / US-Turkey",
    credibility: "High",
    role: "Validation source",
    domains: ["x-account:amberinzaman"],
    status: "Active",
    notes:
      "Al-Monitor correspondent. English-language. Covers Kurdish issue well. Handle: @amberinzaman.",
  },
  {
    id: "tr-source-murat-yetkin",
    name: "Murat Yetkin",
    type: "X account",
    coverage: "Turkey politics / security / foreign policy",
    credibility: "High",
    role: "Deep background",
    domains: ["x-account:yetkinreport", "yetkinreport.com"],
    status: "Active",
    notes:
      "Former diplomatic journalist. Independent. Good for security angle. Handle: @yetkinreport.",
  },
  {
    id: "tr-source-hasan-kosebalaban",
    name: "Hasan Kösebalaban",
    type: "X account",
    coverage: "Turkey foreign policy / security",
    credibility: "High",
    role: "Specialized signal",
    domains: ["x-account:hkosebalaban"],
    status: "Active",
    notes:
      "Academic background. Use for foreign policy and defense stories. Handle: @hkosebalaban.",
  },
  {
    id: "tr-source-murat-agirel",
    name: "Murat Ağırel",
    type: "X account",
    coverage: "Turkey politics / investigative / corruption",
    credibility: "Medium",
    role: "Early signal - investigative lead",
    domains: ["x-account:muratagirel"],
    status: "Needs curation",
    notes:
      "Breaks investigative stories. Cross-check before using. High-impact when verified. Handle: @muratagirel.",
  },
  {
    id: "tr-source-ismail-saymaz",
    name: "İsmail Saymaz",
    type: "X account",
    coverage: "Turkey politics / parliamentary",
    credibility: "Medium",
    role: "Political signal",
    domains: ["x-account:ismail_saymaz"],
    status: "Needs curation",
    notes:
      "Opposition-leaning. Good for political insider info. Verify claims independently. Handle: @ismail_saymaz.",
  },
  {
    id: "tr-source-nevsin-mengu",
    name: "Nevşin Mengü",
    type: "X account",
    coverage: "Turkey politics / society",
    credibility: "Medium",
    role: "Political signal",
    domains: ["x-account:nevsinmengu"],
    status: "Needs curation",
    notes:
      "Opposition lean. Good for political sentiment. Not a breaking news source. Handle: @nevsinmengu.",
  },
  {
    id: "tr-source-cuneyt-ozdemir",
    name: "Cüneyt Özdemir",
    type: "Social signal",
    coverage: "Turkey politics / society / economy",
    credibility: "Medium",
    role: "Public sentiment - reach",
    domains: ["x-account:cuneyt_ozdemir"],
    status: "Needs curation",
    notes:
      "Large audience. YouTube-first. Good for gauging public conversation. Not a primary news source. Handle: @cuneyt_ozdemir.",
  },
  {
    id: "tr-source-ibrahim-haskologlu",
    name: "İbrahim Haskoloğlu",
    type: "X account",
    coverage: "Turkey data leaks / government accountability / digital rights",
    credibility: "Medium",
    role: "Early signal - investigative lead",
    domains: ["x-account:haskologlu"],
    status: "Watch",
    notes:
      "Breaks data leak and accountability stories. Detention history; sensational framing possible, cross-check everything. High reach (1M+). Handle: @haskologlu.",
  },
];
